### ISSUE TITLE
DURATION must have a single duration string

### ISSUE THREAD

**Issue by Jab2870** [jspricke/remind-caldav#13] opened 2020-10-11 15:02 UTC
Hi,

I am trying to backup a caldav calendar so I can use it with remind. However, I am getting the following issue:

```
$ ./dav2rem.py -r 'http://domain/path/to/calendar' -u 'username' -i ./testfile
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/vobject/icalendar.py", line 1494, in transformToNative
    return Duration.transformToNative(obj)
  File "/usr/lib/python3.8/site-packages/vobject/icalendar.py", line 1454, in transformToNative
    raise ParseError("DURATION must have a single duration string.")
vobject.base.ParseError: 'DURATION must have a single duration string.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/vobject/icalendar.py", line 1731, in stringToDateTime
    year = int(s[0:4])
ValueError: invalid literal for int() with base 10: 'P'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/vobject/icalendar.py", line 1501, in transformToNative
    dt = DateTimeBehavior.transformToNative(obj)
  File "/usr/lib/python3.8/site-packages/vobject/icalendar.py", line 756, in transformToNative
    obj.value = parseDtstart(obj)
  File "/usr/lib/python3.8/site-packages/vobject/icalendar.py", line 1956, in parseDtstart
    return stringToDateTime(contentline.value, tzinfo)
  File "/usr/lib/python3.8/site-packages/vobject/icalendar.py", line 1741, in stringToDateTime
    raise ParseError("'{0!s}' is not a valid DATE-TIME".format(s))
vobject.base.ParseError: "'P' is not a valid DATE-TIME"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./dav2rem.py", line 95, in <module>
    main()
  File "./dav2rem.py", line 91, in main
    rem.append_vobject(readOne(vevent.data))
  File "/usr/lib/python3.8/site-packages/vobject/base.py", line 1155, in readOne
    return next(readComponents(stream, validate, transform, ignoreUnreadable,
  File "/usr/lib/python3.8/site-packages/vobject/base.py", line 1128, in readComponents
    component.transformChildrenToNative()
  File "/usr/lib/python3.8/site-packages/vobject/base.py", line 674, in transformChildrenToNative
    child.transformChildrenToNative()
  File "/usr/lib/python3.8/site-packages/vobject/base.py", line 674, in transformChildrenToNative
    child.transformChildrenToNative()
  File "/usr/lib/python3.8/site-packages/vobject/base.py", line 673, in transformChildrenToNative
    child = child.transformToNative()
  File "/usr/lib/python3.8/site-packages/vobject/base.py", line 185, in transformToNative
    return self.behavior.transformToNative(self)
  File "/usr/lib/python3.8/site-packages/vobject/icalendar.py", line 1506, in transformToNative
    raise ParseError(msg)
vobject.base.ParseError: At line 83: TRIGGER with no VALUE not recognized as DURATION or as DATE-TIME
```
If there is anything else I can do to help debug this, please let me know. I have just cloned the repo from github so I will be using the latest versions

**Comment by jspricke** [comment] 2020-10-11 15:27
Hi Jonathan,

can you add a print(vevent.data) here: https://github.com/jspricke/remind-caldav/blob/master/dav2rem.py#L84 (that's line 91 in your modified version) and post the last event?
Also, which version of python3-caldav do you use?

**Comment by Jab2870** [comment] 2020-10-11 16:52
Thank you so much for your quick response. First, the easy one:

```
$ pip show caldav
Name: caldav
Version: 0.7.0
Summary: CalDAV (RFC4791) client library
Home-page: https://github.com/python-caldav/caldav
Author: Cyril Robert
Author-email: cyril@hippie.io
License: GPL
Location: /usr/lib/python3.8/site-packages
Requires: vobject, lxml, requests, six
Required-by: remind-caldav
```

Here is the last event:

```
BEGIN:VCALENDAR
PRODID:Microsoft Exchange Server
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/London
BEGIN:STANDARD
DTSTART:16010101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0000
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T010000
TZOFFSETFROM:+0000
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
UID:<REDACTED>
SUMMARY;LANGUAGE=en-US:<REDACTED>
DTSTART;TZID="Europe/London":20201007T090000
DTEND;TZID="Europe/London":20201007T163000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20200731T131601Z
TRANSP:TRANSPARENT
STATUS:CONFIRMED
SEQUENCE:0
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-OWNERAPPTID:<REDACTED>
X-MICROSOFT-CDO-BUSYSTATUS:FREE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
LAST-MODIFIED:20200731T131601Z
BEGIN:VALARM
DESCRIPTION:REMINDER
TRIGGER;RELATED=START:P
ACTION:DISPLAY
END:VALARM
END:VEVENT
END:VCALENDAR
```

Thanks again for your help

**Comment by jspricke** [comment] 2020-10-11 17:00
The relevant part is:
```
TRIGGER;RELATED=START:P
```

There is a PR for the vobject library here: https://github.com/eventable/vobject/pull/141. You can probably patch it in locally to make it work for you.

Closing as not a bug in remind-caldav.

**Closed by jspricke** 2020-10-11 17:00 UTC
