### ISSUE TITLE
multiple calendars

### ISSUE THREAD

**Issue by gour** [jspricke/remind-caldav#19] opened 2022-07-03 11:21 UTC
Hello,

I'm using Baikal server to sync multiple addressbooks/calendars between my desktop and Android phones and considering to use `remind` on the desktop for calendar events, but wonder whether it is possible to sync multiple calendars?

**Comment by jspricke** [comment] 2022-07-03 14:36
Hi,

remind-caldav syncs one calendar URL to one remind file. You can run it multiple times for multiple calendars.

I'm closing this as it is not a bug but feel free to ask more questions (here).

**Closed by jspricke** 2022-07-03 14:36 UTC
